markdown: kramdown
theme: jekyll-theme-hacker

# Site settings
title: root@atm-infosec.github.io
author: atm
description: Infosec newbie on his journey.
plugins:
    - jekyll-sitemap
    - jekyll-paginate
    - jekyll-seo-tag